---
- name: Fetch IPA ca.crt
  tags:
    - ipaserver-replica
    - ipa-install
    - fetch
  fetch:
    src=/etc/ipa/ca.crt
    dest={{ ipa_data_dir }}/ca.crt
    flat=yes
  delegate_to: "{{item}}"
  with_items: "{{ groups['ipamaster'] }}"
  
- name: Copy IPA ca.crt to all machines
  tags:
    - ipaserver-replica
    - ipa-install
  copy:
    src={{ ipa_data_dir }}/ca.crt
    dest=/etc/pki/ipa-ca.crt
  
 
- name: install ipa server and dns packages
  yum: name={{ item }} state=present
  with_items:
   - bind
   - bind-pkcs11
   - bind-pkcs11-utils
   - bind-dyndb-ldap
   - ipa-server-dns
   - ipa-server
   - ipa-client
   - ipa-admintools
 
- name: if force uninstall is true, uninstall ipa-server
  tags:
    - uninstall
  command: ipa-server-install --uninstall -U
  ignore_errors: yes
  when: force_uninstall
    
- name: get IPA version
  tags:
    - ipa
  command: ipa --version
  register: ipa_version
  changed_when: false
  
- include: replica43.yml
  when: "'4.3.' in ipa_version.stdout"

- include: replica42.yml
  when: "'4.2.' in ipa_version.stdout"




