---

- name: Add master ipa DNS to /etc/resolv.conf
  tags:
    - ipaserver-replica
    - ipa-install
  lineinfile:
    dest=/etc/resolv.conf
    regexp="^nameserver"
    line="nameserver {{groups['ipamaster'][0]}}"
    insertbefore=yes
    state=present
    owner=root
    group=root
    mode=0644

- name: join FreeIPA
  tags:
    - ipa-client
    - ipa-install
  command: >
    ipa-client-install -U
    --principal admin
    --password {{ ipaserver_admin_password }}
    {{ '--mkhomedir' if ipaserver_mkhomedir | default(True) else '' }}
    {{ '--ssh-trust-dns' if ipaserver_ssh_trust_dns | default(True) else '' }}
    --ca-cert-file /etc/pki/ipa-ca.crt
    --force-join
  ignore_errors: true
      
- name: install replica
  tags:
    - ipaserver-replica
    - ipa-install
  command: >
    ipa-replica-install -U
    --password {{ vault_ipaserver_dir_admin_password }}
    --admin-password {{ vault_ipaserver_admin_password }}
    --ip-address {{ ansible_default_ipv4.address }}
    {{ '--forwarder=%s' % ipaserver_dns_forwarder
       if ipaserver_dns_forwarder | default(False) else '--no-forwarders' }}
    {{ '--mkhomedir' if ipaserver_mkhomedir | default(True) else '' }}
    {{ '--setup-dns' if ipaserver_setup_dns | default(True) else '' }}
    {{ '--ssh-trust-dns' if ipaserver_ssh_trust_dns | default(True) else '' }}
    --skip-conncheck
  args:
    creates:
      /etc/ipa/REPLICA_INSTALLED
